// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Search for tracks using yt-dlp
Future<List<SearchResult>> search(
        {required String query, required int limit}) =>
    RustLib.instance.api.crateApiSearch(query: query, limit: limit);

/// Get stream information for a video
Future<StreamInfo> getStreamInfo({required String videoId}) =>
    RustLib.instance.api.crateApiGetStreamInfo(videoId: videoId);

/// Get playlist information
Future<PlaylistInfo> getPlaylist({required String url}) =>
    RustLib.instance.api.crateApiGetPlaylist(url: url);

/// Ensure yt-dlp is installed and up to date
Future<bool> ensureInstalled() =>
    RustLib.instance.api.crateApiEnsureInstalled();

/// Get yt-dlp version
Future<String> getVersion() => RustLib.instance.api.crateApiGetVersion();
