// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field


// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';




                abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
                  RustLibApiImplPlatform({
                    required super.handler,
                    required super.wire,
                    required super.generalizedFrbRustBinding,
                    required super.portManager,
                  });

                  

                  @protected String dco_decode_String(dynamic raw);

@protected bool dco_decode_bool(dynamic raw);

@protected double dco_decode_box_autoadd_f_64(dynamic raw);

@protected int dco_decode_box_autoadd_u_32(dynamic raw);

@protected double dco_decode_f_64(dynamic raw);

@protected List<PlaylistEntry> dco_decode_list_playlist_entry(dynamic raw);

@protected Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

@protected List<SearchResult> dco_decode_list_search_result(dynamic raw);

@protected List<Thumbnail> dco_decode_list_thumbnail(dynamic raw);

@protected String? dco_decode_opt_String(dynamic raw);

@protected double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

@protected int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

@protected PlaylistEntry dco_decode_playlist_entry(dynamic raw);

@protected PlaylistInfo dco_decode_playlist_info(dynamic raw);

@protected SearchResult dco_decode_search_result(dynamic raw);

@protected StreamInfo dco_decode_stream_info(dynamic raw);

@protected Thumbnail dco_decode_thumbnail(dynamic raw);

@protected int dco_decode_u_32(dynamic raw);

@protected int dco_decode_u_8(dynamic raw);

@protected String sse_decode_String(SseDeserializer deserializer);

@protected bool sse_decode_bool(SseDeserializer deserializer);

@protected double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

@protected int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

@protected double sse_decode_f_64(SseDeserializer deserializer);

@protected List<PlaylistEntry> sse_decode_list_playlist_entry(SseDeserializer deserializer);

@protected Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

@protected List<SearchResult> sse_decode_list_search_result(SseDeserializer deserializer);

@protected List<Thumbnail> sse_decode_list_thumbnail(SseDeserializer deserializer);

@protected String? sse_decode_opt_String(SseDeserializer deserializer);

@protected double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

@protected int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

@protected PlaylistEntry sse_decode_playlist_entry(SseDeserializer deserializer);

@protected PlaylistInfo sse_decode_playlist_info(SseDeserializer deserializer);

@protected SearchResult sse_decode_search_result(SseDeserializer deserializer);

@protected StreamInfo sse_decode_stream_info(SseDeserializer deserializer);

@protected Thumbnail sse_decode_thumbnail(SseDeserializer deserializer);

@protected int sse_decode_u_32(SseDeserializer deserializer);

@protected int sse_decode_u_8(SseDeserializer deserializer);

@protected int sse_decode_i_32(SseDeserializer deserializer);

@protected void sse_encode_String(String self, SseSerializer serializer);

@protected void sse_encode_bool(bool self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

@protected void sse_encode_f_64(double self, SseSerializer serializer);

@protected void sse_encode_list_playlist_entry(List<PlaylistEntry> self, SseSerializer serializer);

@protected void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer);

@protected void sse_encode_list_search_result(List<SearchResult> self, SseSerializer serializer);

@protected void sse_encode_list_thumbnail(List<Thumbnail> self, SseSerializer serializer);

@protected void sse_encode_opt_String(String? self, SseSerializer serializer);

@protected void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

@protected void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

@protected void sse_encode_playlist_entry(PlaylistEntry self, SseSerializer serializer);

@protected void sse_encode_playlist_info(PlaylistInfo self, SseSerializer serializer);

@protected void sse_encode_search_result(SearchResult self, SseSerializer serializer);

@protected void sse_encode_stream_info(StreamInfo self, SseSerializer serializer);

@protected void sse_encode_thumbnail(Thumbnail self, SseSerializer serializer);

@protected void sse_encode_u_32(int self, SseSerializer serializer);

@protected void sse_encode_u_8(int self, SseSerializer serializer);

@protected void sse_encode_i_32(int self, SseSerializer serializer);
                }
                


// Section: wire_class

class RustLibWire implements BaseWire {
            RustLibWire.fromExternalLibrary(ExternalLibrary lib);

            
        }
        @JS('wasm_bindgen') external RustLibWasmModule get wasmModule;

        @JS() @anonymous extension type RustLibWasmModule._(JSObject _) implements JSObject {
            
        }
        