// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Playlist entry from yt-dlp
class PlaylistEntry {
  final String id;
  final String title;
  final double? duration;
  final List<Thumbnail> thumbnails;
  final String? channel;

  const PlaylistEntry({
    required this.id,
    required this.title,
    this.duration,
    required this.thumbnails,
    this.channel,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      duration.hashCode ^
      thumbnails.hashCode ^
      channel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaylistEntry &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          duration == other.duration &&
          thumbnails == other.thumbnails &&
          channel == other.channel;
}

/// Playlist information from yt-dlp
class PlaylistInfo {
  final String id;
  final String title;
  final List<PlaylistEntry> entries;

  const PlaylistInfo({
    required this.id,
    required this.title,
    required this.entries,
  });

  @override
  int get hashCode => id.hashCode ^ title.hashCode ^ entries.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaylistInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          entries == other.entries;
}

/// Search result from yt-dlp
class SearchResult {
  final String id;
  final String title;
  final double? duration;
  final String? thumbnail;
  final String? channel;

  const SearchResult({
    required this.id,
    required this.title,
    this.duration,
    this.thumbnail,
    this.channel,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      duration.hashCode ^
      thumbnail.hashCode ^
      channel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchResult &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          duration == other.duration &&
          thumbnail == other.thumbnail &&
          channel == other.channel;
}

/// Stream information from yt-dlp
class StreamInfo {
  final String streamUrl;
  final double? duration;
  final String? title;
  final String? container;
  final String? codec;

  const StreamInfo({
    required this.streamUrl,
    this.duration,
    this.title,
    this.container,
    this.codec,
  });

  @override
  int get hashCode =>
      streamUrl.hashCode ^
      duration.hashCode ^
      title.hashCode ^
      container.hashCode ^
      codec.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StreamInfo &&
          runtimeType == other.runtimeType &&
          streamUrl == other.streamUrl &&
          duration == other.duration &&
          title == other.title &&
          container == other.container &&
          codec == other.codec;
}

/// Thumbnail information
class Thumbnail {
  final String url;
  final int? width;
  final int? height;

  const Thumbnail({
    required this.url,
    this.width,
    this.height,
  });

  @override
  int get hashCode => url.hashCode ^ width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Thumbnail &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          width == other.width &&
          height == other.height;
}
