// This file will be generated by flutter_rust_bridge_codegen
// For now, we provide a placeholder implementation

/// Native yt-dlp wrapper generated by flutter_rust_bridge
class YtDlpNative {
  /// Search for tracks using yt-dlp
  Future<List<SearchResult>> search({required String query, int limit = 10}) async {
    // TODO: Implement with actual Rust bindings
    throw UnimplementedError('Rust bindings not yet generated');
  }

  /// Get stream information for a video
  Future<StreamInfo> getStreamInfo({required String videoId}) async {
    // TODO: Implement with actual Rust bindings
    throw UnimplementedError('Rust bindings not yet generated');
  }

  /// Get playlist information
  Future<PlaylistInfo> getPlaylist({required String url}) async {
    // TODO: Implement with actual Rust bindings
    throw UnimplementedError('Rust bindings not yet generated');
  }

  /// Ensure yt-dlp is installed
  Future<bool> ensureInstalled() async {
    // TODO: Implement with actual Rust bindings
    throw UnimplementedError('Rust bindings not yet generated');
  }

  /// Get yt-dlp version
  Future<String> getVersion() async {
    // TODO: Implement with actual Rust bindings
    throw UnimplementedError('Rust bindings not yet generated');
  }
}

/// Search result from yt-dlp
class SearchResult {
  final String id;
  final String title;
  final double? duration;
  final String? thumbnail;
  final String? channel;

  SearchResult({
    required this.id,
    required this.title,
    this.duration,
    this.thumbnail,
    this.channel,
  });
}

/// Stream information from yt-dlp
class StreamInfo {
  final String streamUrl;
  final double? duration;
  final String? title;
  final String? container;
  final String? codec;

  StreamInfo({
    required this.streamUrl,
    this.duration,
    this.title,
    this.container,
    this.codec,
  });
}

/// Playlist information from yt-dlp
class PlaylistInfo {
  final String id;
  final String title;
  final List<PlaylistEntry> entries;

  PlaylistInfo({
    required this.id,
    required this.title,
    required this.entries,
  });
}

/// Playlist entry from yt-dlp
class PlaylistEntry {
  final String id;
  final String title;
  final double? duration;
  final List<Thumbnail> thumbnails;
  final String? channel;

  PlaylistEntry({
    required this.id,
    required this.title,
    this.duration,
    required this.thumbnails,
    this.channel,
  });
}

/// Thumbnail information
class Thumbnail {
  final String url;
  final int? width;
  final int? height;

  Thumbnail({
    required this.url,
    this.width,
    this.height,
  });
}