// This file provides a wrapper around the generated Rust bindings

import 'api.dart' as api;
import 'lib.dart';

/// Native yt-dlp wrapper generated by flutter_rust_bridge
class YtDlpNative {
  /// Search for tracks using yt-dlp
  Future<List<SearchResult>> search(
      {required String query, int limit = 10}) async {
    return await api.search(query: query, limit: limit);
  }

  /// Get stream information for a video
  Future<StreamInfo> getStreamInfo({required String videoId}) async {
    return await api.getStreamInfo(videoId: videoId);
  }

  /// Get playlist information
  Future<PlaylistInfo> getPlaylist({required String url}) async {
    return await api.getPlaylist(url: url);
  }

  /// Ensure yt-dlp is installed
  Future<bool> ensureInstalled() async {
    return await api.ensureInstalled();
  }

  /// Get yt-dlp version
  Future<String> getVersion() async {
    return await api.getVersion();
  }
}